# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
import pygame
from pygame.locals import *
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.resize(713, 512)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        os.environ['SDL_WINDOWID'] = str(self.centralwidget.winId())
        os.environ['SDL_VIDEODRIVER'] = 'windib'

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
   

def gameloop():

    #variables
    backx = 0
    backy = 0
    backvelo = 0
    treex = 550
    treey = 282

    #treevelo = 0
    dragx = 50
    dragy = 275
    walkpoint = 0
    game = False
    jump = False
    gravity = 7
    score = 0
    gameover = False
    gameSpeed = 3

    while True:

        #colours
        white = (255, 255, 255)
        black = (0, 0, 0)

        for event in pygame.event.get():
            if event.type == QUIT:
                pygame.quit()

            if event.type == KEYDOWN:
                if event.key == K_UP:
                    if dragy == 275:
                        jump = True
                        backvelo = gameSpeed
                        game = True
                if event.key == K_SPACE:
                    if gameover == True:
                        gameloop()

        if backx == -600:
            backx = 0
        if treex < -1600:
            treex = 550

        #jump
        if 276 > dragy > 125:
            if jump == True:
                dragy -= 7
        else:
            jump = False

        if dragy < 275:
            if jump == False:
                dragy += gravity

        #collision
        if treex < dragx + 50 < treex + 70 and treey < dragy + 50 < treey + 50:
            backvelo = 0            
            walkpoint = 0
            game = False
            gameover = True
        if treex + 400 < dragx + 50 < treex + 470 and treey < dragy + 50 < treey + 50:
            backvelo = 0            
            walkpoint = 0
            game = False
            gameover = True
        if treex + 800 < dragx + 50 < treex + 870 and treey < dragy + 50 < treey + 50:
            backvelo = 0            
            walkpoint = 0
            game = False
            gameover = True
        if treex + 1200 < dragx + 50 < treex + 1270 and treey < dragy + 50 < treey + 50:
            backvelo = 0            
            walkpoint = 0
            game = False
            gameover = True
        if game == True:
            score += 1


        scr.fill(white)
        text = font.render("Score: " + str(score), True, black)
        text1 = font.render("Game over! Press Space to continue ", True, black)
        backx -= backvelo
        treex -= backvelo

        scr.blit(background, [backx, backy])
        scr.blit(background, [backx+600, backy])
        scr.blit(text, [400, 150])
        if gameover == True:
            scr.blit(text1, [50, 350])

        #walking legs
        scr.blit(walk[walkpoint], [dragx, dragy])
        if game == True:
            walkpoint += 1
            if walkpoint > 15:
                walkpoint = 0
        scr.blit(tree, [treex, treey])
        scr.blit(tree1, [treex + 400, treey])
        scr.blit(tree2, [treex + 800, treey])
        scr.blit(tree3, [treex + 1200, treey])
        scr.blit(tree4, [treex + 1600, treey])
        pygame.display.update()  

#modules initialized
pygame.init()

#screen size
scr = pygame.display.set_mode((600,500))
pygame.display.set_caption("Trex try1")

app = QtWidgets.QApplication(sys.argv)
ui = Ui_MainWindow()
ui.setupUi(scr)
ui.show()

#font
font = pygame.font.Font("freesansbold.ttf", 20)

#images
background = pygame.image.load("images/background.png")
dragon = pygame.image.load("images/dra1.png")
dragon = pygame.transform.scale(dragon, (50,50))
dragon2 = pygame.image.load("images/dra2.png")
dragon2 = pygame.transform.scale(dragon2, (50,50))
dragon3 = pygame.image.load("images/dra3.png")
dragon3 = pygame.transform.scale(dragon3, (50,50))
dragon4 = pygame.image.load("images/dra4.png")
dragon4 = pygame.transform.scale(dragon4, (50,50))
dragon5 = pygame.image.load("images/dra6.png")
dragon5 = pygame.transform.scale(dragon5, (50,50))

walk = [dragon, dragon, dragon, dragon, dragon2, dragon2, dragon2, dragon2, dragon3, dragon3, dragon3, dragon3, dragon4, dragon4, dragon4, dragon4]

tree = pygame.image.load("images/tree.png")
tree = pygame.transform.scale(tree, (70, 50))
tree1 = pygame.image.load("images/tree1.png")
tree1 = pygame.transform.scale(tree1, (100, 60))
tree2 = pygame.image.load("images/tree2.png")
tree2 = pygame.transform.scale(tree2, (90, 60))
tree3 = pygame.image.load("images/tree3.png")
tree3 = pygame.transform.scale(tree3, (45, 60))
tree4 = pygame.image.load("images/tree4.png")
tree4 = pygame.transform.scale(tree4, (70, 60))

gameloop()    
#end of the game